name: Build angular and upload dist as artifact
on:
  push:
    branches: [ 'master' ]
  pull_request:
    branches: [ 'master' ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: npm ci

      - run: npm run build:prod

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist/annervisser-website-terminal/browser/
